- CHANGELOG.rst
- docs/css/guidelines.rst
> add universal selector guideline

- CHANGELOG.rst
- boilerplate.json
- static/js/modules/README.rst
- static/js/modules/ckeditor.wysiwyg.js
> Release 3.0.10

- CHANGELOG.rst
- static/js/modules/ckeditor.wysiwyg.js
Depends on CKEditor documentation here: http://docs.ckeditor.com/#!/api/CKEDITOR.dtd
> Empty span remove in CKEditor

- docs/general/whatsinside.rst
- docs/index.rst
> First amends

- CHANGELOG.rst
- docs/codestyle/javascript.rst
this PR moves jQuery into it's own section in codestyle + adds a not on using ajax with promises
> codestyle: add note about the ajax promises

- docs/testing/general.rst
- docs/testing/index.rst
- docs/testing/integration_tests.rst
- docs/testing/unit_tests.rst
- gulpfile.js
- tests/integration/pages/page.dummy.js
- tests/integration/specs/spec.dummy.js
- tests/protractor.conf.js
**This pull request adds integration tests documentation**
Also:
- typos fixed for ```unit_tests.rst``` and ```integration_tests.rst```
- updated links in ```general.rst``` and ```index.rst```
- ```gulpfile.js``` updated with new path to integration tests
- added dummy page object ```page.dummy.js```
> Added integration tests documentation

- CHANGELOG.rst
- browserlist
- browserslist
- docs/testing/general.rst
- package.json
- tests/base.conf.js
- tests/integration/specs/spec.dummy.js
- tests/karma.conf.js
- tests/protractor.conf.js
> Browserlist integration

- .travis.yml
- private/sass/sites/_custom.scss
- templates/404.html
missing indentation, use new travis infrastructure...
> File Cleanup

- docs/testing/services.rst
**This pull request updates services.rst to describe secure tokens usage in .travis.yml**
> Added secure tokens description

- docs/contribution/index.rst
as this boilerplate affects a large portion of projects, we need more opinions than just one for PRs
> Make PR contribution more clear

- gulpfile.js
- package.json
documentation will follow separately
> Add debugging feature

- .editorconfig
- CHANGELOG.rst
- package.json
- private/sass/layout/_buttons.scss
- private/sass/mixins/_other.scss
- static/js/addons/ckeditor.wysiwyg.js
> Fix issues

- .travis.yml
- AUTHORS.rst
**This pull request updates AUTHORS.rst**
Also:
- Adds secure tokens explanation to ```.travis.yml```
> Updated AUTHORS.rst

- CHANGELOG.rst
- boilerplate.json
- docs/general/installation.rst
- gulpfile.js
- package.json
This allows us to further enhance #20 and fixes current problems with icon generation
> Adding bower support

- .travis.yml
- package.json
> Fix node build

- docs/codestyle/javascript.rst
re-adding lost ajax promises section
> jQuery ajax promises

- CHANGELOG.rst
- boilerplate.json
- docs/codestyle/javascript.rst
- fixed dependency linking for Aldryn
- added docs about ajax promises
> Release 4.0.1

- tools/server/src/wsgi.py
without this the server simply doesn't run for me
> add missing wsgi.py

- CHANGELOG.rst
- boilerplate.json
- templates/includes/menu/langnav.html
> Release 4.0.4

- templates/includes/menu/langnav.html
closes https://github.com/aldryn/aldryn-boilerplate-bootstrap3/issues/148
> show language name in it's language

- CHANGELOG.rst
- docs/Makefile
- docs/codestyle/styles.rst
> Feature: docs output adjustment

- CHANGELOG.rst
Small update for CHANGELOG.rst.
> changelog: remove unnecessary line

- .bowerrc
- CHANGELOG.rst
- templates/base.html
- tools/tasks/bower.js
- tools/tasks/browser.js
- tools/tasks/sass.js
fix broken browser / bower + fix tempate tag load for 1.9 compatibility
> Gulp tasks fixes + url templatetag lib

- CHANGELOG.rst
- templates/base.html
to replace `href="/"` for reference
> add page root definition
